[package]
name = "slump"
version = "0.1.0"
edition = "2021"

[dependencies]
envy = "0.4.2"
serde_json = "1.0.74"
anyhow = "1.0.52"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version= "1.0.133"
